apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: software-techdocs-template
  title: Software TechDocs Template
  description: Template for standardized software documentation using TechDocs
  tags:
    - recommended
    - techdocs
    - documentation
    - software
spec:
  owner: platform-team
  type: documentation
  
  parameters:
    - title: Basic Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Component Name
          type: string
          description: Unique name for the software component
          pattern: '^([a-z0-9\-])+$'
          ui:autofocus: true
          ui:help: 'Use lowercase letters, numbers, and hyphens only'
        description:
          title: Description
          type: string
          description: A brief description of the software component
        owner:
          title: Owner
          type: string
          description: Owner of the component (team or individual)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        type:
          title: Component Type
          type: string
          description: Type of the software component
          default: service
          enum:
            - service
            - website
            - library
            - api
          enumNames:
            - Service
            - Website
            - Library
            - API
        lifecycle:
          title: Lifecycle
          type: string
          description: Current lifecycle stage of the component
          default: production
          enum:
            - experimental
            - development
            - production
          enumNames:
            - Experimental
            - Development
            - Production

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
              - bitbucket.org
        targetPath:
          title: Target Path
          type: string
          description: Path in the repository where docs will be added
          default: ./
          ui:help: 'Leave as ./ to add to root directory'

    - title: Kubernetes Configuration (Optional)
      properties:
        deployKubernetes:
          title: Deployed on Kubernetes?
          type: boolean
          description: Is this component deployed on Kubernetes?
          default: false
        kubernetesNamespace:
          title: Kubernetes Namespace
          type: string
          description: Kubernetes namespace where the component is deployed
          ui:help: 'Required if deployed on Kubernetes'
          dependencies:
            deployKubernetes:
              oneOf:
                - properties:
                    deployKubernetes:
                      const: true
                  required:
                    - kubernetesNamespace
                - properties:
                    deployKubernetes:
                      const: false

  steps:
    - id: fetch
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          type: ${{ parameters.type }}
          lifecycle: ${{ parameters.lifecycle }}
          deployKubernetes: ${{ parameters.deployKubernetes }}
          kubernetesNamespace: ${{ parameters.kubernetesNamespace }}
          repoSlug: ${{ (parameters.repoUrl | parseRepoUrl)['owner'] }}/${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}

    - id: publish
      name: Publish to Repository
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'Add TechDocs documentation for ${{ parameters.name }}'
        branchName: 'add-techdocs-${{ parameters.name }}'
        description: |
          This PR adds standardized TechDocs documentation for ${{ parameters.name }}.
          
          ## What's included:
          - Complete documentation structure
          - Catalog registration file
          - MkDocs configuration
          - Template markdown files for all sections
          
          Please review and merge to enable TechDocs for this component.
        targetPath: ${{ parameters.targetPath }}
        sourcePath: .
        allowedHosts: ['github.com']

    - id: register
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ parameters.repoUrl }}
        catalogInfoPath: '${{ parameters.targetPath }}/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ parameters.repoUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Pull Request
        url: ${{ steps.publish.output.remoteUrl }}