apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  {{#if values.tags}}
  tags:
    {{#each values.tags}}
    - {{this}}
    {{/each}}
  {{/if}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoSlug }}
spec:
  type: documentation
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  {{#if values.system}}
  system: ${{ values.system }}
  {{/if}}
