apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  {% if values.tags and (values.tags | length) > 0 %}
  tags:
  {% for tag in values.tags %}
    - {{ tag }}
  {% endfor %}
  {% endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoSlug }}
spec:
  type: documentation
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  {% if values.system %}
  system: ${{ values.system }}
  {% endif %}
  {% if values.domain %}
  domain: ${{ values.domain }}
  {% endif %}
