apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hardware-techdocs-template
  title: "Hardware TechDocs + Catalog"
  description: "Buat repo dokumentasi hardware (TechDocs) + catalog-info.yaml (tanpa anotasi Kubernetes)."
  tags: [techdocs, documentation, hardware]
spec:
  owner: group:platform
  type: documentation

  parameters:
    - title: Project Info
      required: [name, description, lifecycle]
      properties:
        name:
          title: Name
          type: string
          description: "Nama project / produk hardware (dipakai untuk componentId)."
          ui:field: EntityNamePicker
          ui:options:
            allowedKinds: [Component]
        description:
          title: Description
          type: string
          description: "Deskripsi singkat dokumentasi hardware."
        lifecycle:
          title: Lifecycle
          type: string
          default: production
          enum: [develop, production]
        tags:
          title: Tags
          type: array
          items:
            type: string
          default: ["techdocs", "hardware"]

    - title: Catalog Metadata
      required: [owner]
      properties:
        owner:
          title: Owner
          type: string
          description: "Owner katalog (mis. user:alice atau group:platform)."
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group, User]
        system:
          title: System
          type: string
          description: "(Opsional) system Backstage."
        domain:
          title: Domain
          type: string
          description: "(Opsional) domain Backstage."

    - title: Repository
      required: [repoUrl, repoSlug]
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: "Target repo GitHub (format: github.com?owner=<org>&repo=<repo>)."
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: ["github.com"]
        repoSlug:
          title: GitHub Project Slug
          type: string
          description: "Format owner/repo (dipakai untuk annotation github.com/project-slug)."
          examples: ["my-org/hw-docs"]
        defaultBranch:
          title: Default Branch
          type: string
          default: main
        repoVisibility:
          title: Repository Visibility
          type: string
          default: private
          enum: [private, public]

  steps:
    - id: fetchBase
      name: Fetch & Template skeleton
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - ".github/**"
          - "docs/stylesheets/**"
        values:
          name: ${{ parameters.name }}
          componentId: ${{ parameters.name | lower | replace(' ', '-') }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          domain: ${{ parameters.domain }}
          lifecycle: ${{ parameters.lifecycle }}
          tags: ${{ parameters.tags }}
          repoSlug: ${{ parameters.repoSlug }}
          site_name: ${{ parameters.name }}
          repo_main_branch: ${{ parameters.defaultBranch }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: ${{ parameters.defaultBranch }}
        repoVisibility: ${{ parameters.repoVisibility }}
        protectDefaultBranch: true

    - id: register
      name: Register in Backstage Catalog
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/${{ parameters.repoSlug }}/blob/${{ parameters.defaultBranch }}/catalog-info.yaml

  output:
    links:
      - title: Open Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: "Repository URL"
        content: ${{ steps.publish.output.remoteUrl }}
      - title: "Entity Ref"
        content: ${{ steps.register.output.entityRef }}
