apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hardware-division-doc-template
  title: Hardware Documentation Standard Template
  description: Standarisasi dokumentasi hardware division, otomatis setup struktur MkDocs & TechDocs.
  tags:
    - division-standard
    - techdocs
    - documentation
    - hardware
spec:
  owner: platform-team
  type: service
  parameters:
    - title: Project Information
      required:
        - name
        - description
        - type
        - owner
      properties:
        name:
          title: Project Name
          type: string
          description: Nama dokumentasi/project (lowercase, dash allowed)
          pattern: '^([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$'
        description:
          title: Description
          type: string
          description: Deskripsi singkat tentang hardware project
        owner:
          title: Owner
          type: string
          description: Tim atau individu yang bertanggung jawab
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        type:
          title: Type
          type: string
          description: Jenis hardware (device, component, system, dsb)
          enum:
            - device
            - component
            - system
            - infrastructure
            - other
          default: device
    - title: Repository Information
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Pilih repository yang sudah ada atau buat baru
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com

  steps:
    - id: fetch
      name: Fetch Documentation Skeleton
      action: fetch:template
      input:
        url: https://github.com/Azer2401/techdocs-template/tree/main/hardware-techdocs/skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          type: ${{ parameters.type }}
          repoSlug: ${{ parameters.repoUrl }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Add standardized documentation structure"
        description: ${{ parameters.description }}
        branchName: add-docs-${{ parameters.name }}
        targetPath: ""

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
