apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  {{#if values.tags}}
  tags:
    {{#each values.tags}}
    - {{this}}
    {{/each}}
  {{/if}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoSlug }}
    {{#if values.deployKubernetes}}
    backstage.io/kubernetes-id: ${{ values.name }}
    {{#if values.kubernetesNamespace}}
    backstage.io/kubernetes-namespace: ${{ values.kubernetesNamespace }}
    {{/if}}
    {{#if values.kubernetesCluster}}
    backstage.io/kubernetes-cluster: ${{ values.kubernetesCluster }}
    {{/if}}
    {{/if}}
spec:
  type: ${{ values.type }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  {{#if values.system}}
  system: ${{ values.system }}
  {{/if}}
